BOOL NtUserSetKeyboardState(PBYTE);//1
DWORD NtGdiDvpColorControl(HANDLE,OUT PDD_VPORTCOLORDATA);//2
NTSTATUS NtUserCreateLocalMemHandle(HANDLE,PVOID,DWORD,PDWORD);//4
NTSTATUS NtGdiSetUMPDSandboxState(BOOL);//1
BOOL NtGdiSetColorAdjustment(HDC,PCOLORADJUSTMENT);//2
BOOL NtGdiForceUFIMapping(HDC,PUNIVERSAL_FONT_ID);//2
HWND NtUserGetForegroundWindow(VOID);//0
BOOL NtGdiDwmCreatedBitmapRemotingOutput(VOID);//0
DWORD NtGdiDdCanCreateSurface(HANDLE,OUT PDD_CANCREATESURFACEDATA);//2
BOOL NtGdiEngPlgBlt(SURFOBJ*,SURFOBJ*,SURFOBJ*,CLIPOBJ*,XLATEOBJ*,COLORADJUSTMENT*,PPOINTL,POINTFIX*,LPRECTL,PPOINTL,ULONG);//11
BOOL NtGdiRemoveFontResourceW(PWCHAR,ULONG,ULONG,ULONG,DWORD,DESIGNVECTOR*);//6
BOOL NtGdiIcmBrushInfo(HDC,HBRUSH,PBITMAPINFO,PVOID,OUT PULONG,OUT PDWORD,OUT PBOOL,ULONG);//8
BOOL NtUserQuerySendMessage(OUT LPMSG);//1
DWORD NtGdiSetBoundsRect(HDC,LPRECT,DWORD);//3
BOOL NtUserDestroyCursor(HANDLE,BOOL);//2
BOOL NtUserRealWaitMessageEx(DWORD,UINT);//2
UINT NtUserHardErrorControl(HARDERRORCONTROL,HANDLE,OUT PDESKRESTOREDATA);//3
BOOL NtGdiGetBitmapDimension(HBITMAP,OUT LPSIZE);//2
BOOL NtGdiEndGdiRendering(HBITMAP,BOOL,OUT PBOOL,PVOID);//4
DWORD NtGdiDdUnlock(HANDLE,OUT PDD_UNLOCKDATA);//2
LONG NtGdiHT_Get8BPPMaskPalette(OUT LPPALETTEENTRY,BOOL,BYTE,USHORT,USHORT,USHORT);//6
BOOL NtGdiEngAlphaBlend(SURFOBJ*,SURFOBJ*,CLIPOBJ*,XLATEOBJ*,LPRECTL,LPRECTL,BLENDOBJ*);//7
INT NtGdiGetTextFaceW(HDC,INT,PWSTR,BOOL);//4
BOOL NtGdiAddRemoteMMInstanceToDC(HDC,DOWNLOADDESIGNVECTOR*,ULONG);//3
BOOL NtGdiCheckBitmapBits(HDC,HANDLE,PVOID,ULONG,DWORD,DWORD,DWORD,PBYTE);//8
BOOL NtUserCloseWindowStation(HWINSTA);//1
DWORD NtGdiGetCharacterPlacementW(HDC,PWSTR,INT,INT,OUT LPGCP_RESULTSW,DWORD);//6
BOOL NtUserWaitForMsgAndEvent(HANDLE);//1
BOOL NtUserCheckWindowThreadDesktop(HWND,DWORD,ULONG);//3
HBITMAP NtGdiCreateSessionMappedDIBSection(HDC,HANDLE,DWORD,LPBITMAPINFO,DWORD,UINT,FLONG,ULONG_PTR);//8
HANDLE NtGdiGetStockObject(INT);//1
UINT NtUserGetDoubleClickTime(VOID);//0
BOOL NtGdiStrokePath(HDC);//1
BOOL NtUserSystemParametersInfo(UINT,UINT,PVOID,UINT);//4
DWORD NtGdiDdBlt(HANDLE,HANDLE,OUT PDD_BLTDATA);//3
BOOL NtGdiSwapBuffers(HDC);//1
LONG NtUserSetWindowLong(HWND,DWORD,LONG,BOOL);//4
BOOL NtGdiChangeGhostFont(KERNEL_PVOID*,BOOL);//2
VOID NtUserModifyUserStartupInfoFlags(DWORD,DWORD);//2
BOOL NtUserFillWindow(HWND,HWND,HDC,HBRUSH);//4
BOOL NtGdiGetUFIPathname(PUNIVERSAL_FONT_ID,PULONG,PWSTR,OUT PULONG,FLONG,OUT PBOOL,OUT PULONG,OUT PVOID,OUT PBOOL,OUT PULONG);//10
BOOL NtUserUnregisterUserApiHook(VOID);//0
HWND NtUserWindowFromPoint(LONG,LONG);//2
NTSTATUS NtUserBuildHwndList(HDESK,HWND,BOOLEAN,ULONG,ULONG,HWND*,PULONG);//7
UINT NtGdiSetSystemPaletteUse(HDC,UINT);//2
BOOL NtUserSetLogonNotifyWindow(HWND);//1
BOOL NtUserUnlockWindowStation(HWINSTA);//1
INT NtGdiExcludeClipRect(HDC,INT,INT,INT,INT);//5
HANDLE NtGdiDvpCreateVideoPort(HANDLE,OUT PDD_CREATEVPORTDATA);//2
BOOL NtUserUpdatePerUserSystemParameters(DWORD,BOOL);//2
HANDLE NtUserSetClipboardData(UINT,HANDLE,PSETCLIPBDATA);//3
BOOL NtUserMNDragOver(LPPOINT,OUT PMNDRAGOVERINFO);//2
DHPDEV NtGdiGetDhpdev(HDEV);//1
DWORD_PTR NtUserCallTwoParam(DWORD_PTR,DWORD_PTR,DWORD);//3
HBITMAP NtGdiCreateBitmapFromDxSurface(HDC,UINT,UINT,DWORD,HANDLE);//5
DWORD NtUserScrollWindowEx(HWND,INT,INT,LPRECT,LPRECT,HRGN,LPRECT,UINT);//8
BOOL NtGdiGetEmbUFI(HDC,OUT PUNIVERSAL_FONT_ID,OUT DESIGNVECTOR*,OUT PULONG,OUT PULONG,OUT FLONG*,OUT KERNEL_PVOID*);//7
WORD NtUserSetClassWord(HWND,INT,WORD);//3
NTSTATUS NtGdiDdUnattachSurface(HANDLE,HANDLE);//2
BOOL NtUserDrawCaptionTemp(HWND,HDC,LPCRECT,HFONT,HICON,PUNICODE_STRING,UINT);//7
BOOL NtGdiExtFloodFill(HDC,INT,INT,COLORREF,UINT);//5
BOOL NtUserThunkedMenuItemInfo(HMENU,UINT,BOOL,BOOL,LPMENUITEMINFOW,PUNICODE_STRING);//6
UINT NtUserSendInput(UINT,LPINPUT,INT);//3
BOOL NtGdiTransparentBlt(HDC,INT,INT,INT,INT,HDC,INT,INT,INT,INT,COLORREF);//11
HDC NtUserBeginPaint(HWND,OUT LPPAINTSTRUCT);//2
HPEN NtGdiSelectPen(HDC,HPEN);//2
HANDLE NtGdiDdGetDxHandle(HANDLE,HANDLE,BOOL);//3
HPEN NtGdiCreatePen(INT,INT,COLORREF,HBRUSH);//4
HWND NtUserGetOpenClipboardWindow(VOID);//0
DWORD NtUserSetInternalWindowPos(HWND,UINT,LPRECT,LPPOINT);//4
BOOL NtGdiInvertRgn(HDC,HRGN);//2
INT NtGdiGetAppClipBox(HDC,OUT LPRECT);//2
BOOL NtGdiGetCharWidthW(HDC,UINT,UINT,PWCHAR,FLONG,PVOID);//6
BOOL NtGdiDdQueryDirectDrawObject(HANDLE,OUT PDD_HALINFO,PDWORD,OUT LPD3DNTHAL_CALLBACKS,OUT LPD3DNTHAL_GLOBALDRIVERDATA,OUT PDD_D3DBUFCALLBACKS,OUT LPDDSURFACEDESC,OUT PDWORD,OUT VIDEOMEMORY*,OUT PDWORD,OUT PDWORD);//11
LONG NtGdiGetDeviceWidth(HDC);//1
BOOL NtGdiSetDeviceGammaRamp(HDC,PVOID);//2
DWORD NtGdiDdGetMoCompFormats(HANDLE,OUT PDD_GETMOCOMPFORMATSDATA);//2
BOOL NtUserUnloadKeyboardLayout(HKL);//1
BOOL NtGdiSetMagicColors(HDC,PALETTEENTRY,ULONG);//3
DWORD NtGdiDdSetExclusiveMode(HANDLE,OUT PDD_SETEXCLUSIVEMODEDATA);//2
HBRUSH NtGdiCreateSolidBrush(COLORREF,HBRUSH);//2
HPEN NtGdiExtCreatePen(ULONG,ULONG,ULONG,ULONG,ULONG_PTR,ULONG_PTR,ULONG,PULONG,ULONG,BOOL,HBRUSH);//11
BOOL NtUserSetCursorContents(HANDLE,PICONINFO);//2
HDC NtGdiOpenDCW(PUNICODE_STRING,DEVMODEW*,PUNICODE_STRING,ULONG,BOOL,HANDLE,PVOID);//7
BOOL NtGdiMoveTo(HDC,INT,INT,OUT LPPOINT);//4
BOOL NtGdiPATHOBJ_bEnumClipLines(PATHOBJ*,ULONG,CLIPLINE*);//3
BOOL NtGdiDwmGetHighColorMode(OUT DXGI_FORMAT*);//1
BOOL NtGdiStrokeAndFillPath(HDC);//1
DWORD_PTR NtUserCallNoParam(DWORD);//1
BOOL NtGdiGetAndSetDCDword(HDC,UINT,DWORD,OUT PDWORD);//4
INT NtGdiGetRandomRgn(HDC,HRGN,INT);//3
INT NtGdiSetMetaRgn(HDC);//1
HBRUSH NtUserGetControlColor(HWND,HWND,HDC,UINT);//4
INT NtGdiGetRgnBox(HRGN,OUT LPRECT);//2
DWORD NtGdiDdGetBltStatus(HANDLE,OUT PDD_GETBLTSTATUSDATA);//2
HBRUSH NtGdiCreateDIBBrush(PVOID,FLONG,UINT,BOOL,BOOL,PVOID);//6
DWORD NtUserGetInternalWindowPos(HWND,LPRECT,LPPOINT);//3
ULONG NtUserCopyAcceleratorTable(HACCEL,LPACCEL,ULONG);//3
HBITMAP NtGdiCreateDIBitmapInternal(HDC,INT,INT,DWORD,PBYTE,LPBITMAPINFO,DWORD,UINT,UINT,FLONG,HANDLE);//11
BOOL NtGdiEudcLoadUnloadLink(PCWSTR,UINT,PCWSTR,UINT,INT,INT,BOOL);//7
DWORD_PTR NtUserGetThreadState(DWORD);//1
BOOL NtGdiMaskBlt(HDC,INT,INT,INT,INT,HDC,INT,INT,HBITMAP,INT,INT,DWORD,DWORD);//13
BOOL NtGdiEqualRgn(HRGN,HRGN);//2
DWORD NtGdiDdGetMoCompBuffInfo(HANDLE,OUT PDD_GETMOCOMPCOMPBUFFDATA);//2
BOOL NtUserGetMenuBarInfo(HWND,LONG,LONG,PMENUBARINFO);//4
BOOL NtGdiMakeObjectXferable(HANDLE,DWORD);//2
BOOL NtGdiEndPath(HDC);//1
DWORD NtUserRemoteRedrawScreen(VOID);//0
LONG NtUserChangeDisplaySettings(PUNICODE_STRING,LPDEVMODEW,DWORD,PVOID);//4
INT NtGdiExtGetObjectW(HANDLE,INT,PVOID);//3
BOOL NtUserSendMessageCallback(HWND,UINT,WPARAM,LPARAM,SENDASYNCPROC,ULONG_PTR);//6
HMONITOR NtUserMonitorFromPoint(POINT,DWORD);//2
BOOL NtGdiSetRectRgn(HRGN,INT,INT,INT,INT);//5
HWND NtUserSetActiveWindow(HWND);//1
HANDLE NtGdiDwmCaptureScreen(LPRECT,DXGI_FORMAT);//2
BOOL NtGdiSetColorSpace(HDC,HCOLORSPACE);//2
BOOL NtUserGetIconSize(HANDLE,UINT,PLONG,PLONG);//4
DWORD NtUserShowScrollBar(HWND,INT,DWORD);//3
BOOL NtGdiUpdateTransform(HDC);//1
BOOL NtGdiResetDC(HDC,LPDEVMODEW,OUT PBOOL,DRIVER_INFO_2W*,PVOID);//5
BOOL NtUserGetCursorInfo(LPCURSORINFO);//1
DWORD NtGdiDdGetMoCompGuids(HANDLE,OUT PDD_GETMOCOMPGUIDSDATA);//2
NTSTATUS NtUserSetInformationThread(HANDLE,USERTHREADINFOCLASS,PVOID,ULONG);//4
HDESK NtUserResolveDesktop(HANDLE,PUNICODE_STRING,BOOL,OUT HWINSTA*);//4
SHORT NtUserGetAsyncKeyState(INT);//1
DWORD NtUserCallHwnd(HWND,DWORD);//2
HBITMAP NtGdiSelectBitmap(HDC,HBITMAP);//2
DWORD NtGdiGetBoundsRect(HDC,OUT LPRECT,DWORD);//3
NTSTATUS NtGdiFlush(VOID);//0
BOOL NtGdiSetBrushOrg(HDC,INT,INT,OUT LPPOINT);//4
DWORD NtGdiD3dValidateTextureStageState(OUT LPD3DNTHAL_VALIDATETEXTURESTAGESTATEDATA);//1
HBITMAP NtGdiCreateDIBSection(HDC,HANDLE,DWORD,LPBITMAPINFO,DWORD,UINT,FLONG,ULONG_PTR,OUT PVOID*);//9
DWORD NtGdiDdSetOverlayPosition(HANDLE,HANDLE,OUT PDD_SETOVERLAYPOSITIONDATA);//3
PVOID NtGdiBRUSHOBJ_pvGetRbrush(BRUSHOBJ*);//1
BOOL NtUserSetMenuDefaultItem(HMENU,UINT,UINT);//3
BOOL NtGdiFillPath(HDC);//1
BOOL NtGdiPtVisible(HDC,INT,INT);//3
HDC NtGdiGetDCforBitmap(HBITMAP);//1
DWORD NtGdiDdLockD3D(HANDLE,OUT PDD_LOCKDATA);//2
BOOL NtGdiGetRealizationInfo(HDC,OUT PFONT_REALIZATION_INFO);//2
BOOL NtUserSendNotifyMessage(HWND,UINT,WPARAM,LPARAM);//4
BOOL NtGdiUpdateColors(HDC);//1
DWORD NtGdiDvpGetVideoPortConnectInfo(HANDLE,OUT PDD_GETVPORTCONNECTDATA);//2
BOOL NtGdiGradientFill(HDC,PTRIVERTEX,ULONG,PVOID,ULONG,ULONG);//6
BOOL NtGdiDeleteClientObj(HANDLE);//1
HWND NtUserCallHwndOpt(HWND,DWORD);//2
BOOL NtUserRedrawWindow(HWND,LPRECT,HRGN,UINT);//4
DWORD NtGdiDdGetFlipStatus(HANDLE,OUT PDD_GETFLIPSTATUSDATA);//2
ULONG_PTR NtUserSetClassLong(HWND,INT,ULONG_PTR,BOOL);//4
DWORD NtUserUpdateInstance(HANDLE,OUT PDWORD,DWORD);//3
BOOL NtGdiAddRemoteFontToDC(HDC,PVOID,ULONG,PUNIVERSAL_FONT_ID);//4
NTSTATUS NtUserBuildPropList(HWND,PVOID,DWORD,PDWORD);//4
DWORD NtUserCheckMenuItem(HMENU,UINT,UINT);//3
BOOL NtGdiD3dContextCreate(HANDLE,HANDLE,HANDLE,OUT D3DNTHAL_CONTEXTCREATEI*);//4
BOOL NtGdiCancelDC(HDC);//1
BOOL NtGdiHLSurfGetInformation(HLSURF,HLSURF_INFORMATION_CLASS,PVOID,OUT PULONG);//4
HMONITOR NtUserMonitorFromRect(LPCRECT,DWORD);//2
BOOL NtUserValidateTimerCallback(LPARAM);//1
ULONG NtGdiXLATEOBJ_cGetPalette(XLATEOBJ*,ULONG,ULONG,PULONG);//4
DWORD NtGdiDdGetInternalMoCompInfo(HANDLE,OUT PDD_GETINTERNALMOCOMPDATA);//2
BOOL NtUserEnumDisplayDevices(PUNICODE_STRING,DWORD,PDISPLAY_DEVICEW,DWORD);//4
BOOL NtUserCheckDesktopByThreadId(DWORD);//1
BOOL NtGdiBitBlt(HDC,INT,INT,INT,INT,HDC,INT,INT,DWORD,DWORD,FLONG);//11
BOOL NtUserSetWindowPos(HWND,HWND,INT,INT,INT,INT,UINT);//7
INT NtGdiExtEscape(HDC,PWCHAR,INT,INT,INT,PSTR,INT,PSTR);//8
BOOL NtGdiDdAttachSurface(HANDLE,HANDLE);//2
BOOL NtUserSetConsoleReserveKeys(HWND,DWORD);//2
BOOL NtUserUnhookWinEvent(HWINEVENTHOOK);//1
HWND NtUserSetParent(HWND,HWND);//2
NTSTATUS NtGdiPATHOBJ_vEnumStartClipLines(PATHOBJ*,CLIPOBJ*,SURFOBJ*,LINEATTRS*);//4
BOOL NtUserSBGetParms(HWND,INT,PSBDATA,LPSCROLLINFO);//4
BOOL NtUserInvalidateRect(HWND,LPRECT,BOOL);//3
DWORD NtGdiDdBeginMoCompFrame(HANDLE,OUT PDD_BEGINMOCOMPFRAMEDATA);//2
BOOL NtUserSetMenu(HWND,HMENU,BOOL);//3
BOOL NtUserMessageCall(HWND,UINT,WPARAM,LPARAM,ULONG_PTR,DWORD,BOOL);//7
DWORD NtGdiGetCharSet(HDC);//1
HRGN NtGdiPathToRegion(HDC);//1
BOOL NtGdiDeleteObjectApp(HANDLE);//1
BOOL NtGdiSetSizeDevice(HDC,INT,INT);//3
BOOL NtUserGetComboBoxInfo(HWND,PCOMBOBOXINFO);//2
INT NtGdiExtSelectClipRgn(HDC,HRGN,INT);//3
INT NtUserGetPriorityClipboardFormat(PUINT,INT);//2
BOOL NtGdiGetColorAdjustment(HDC,OUT PCOLORADJUSTMENT);//2
BOOL NtGdiFillRgn(HDC,HRGN,HBRUSH);//3
DWORD NtGdiDvpGetVideoPortInputFormats(HANDLE,OUT PDD_GETVPORTINPUTFORMATDATA);//2
ULONG NtGdiSetFontEnumeration(ULONG);//1
BOOL NtUserCloseDesktop(HDESK);//1
HPALETTE NtGdiCreateHalftonePalette(HDC);//1
PFD_GLYPHATTR NtGdiFONTOBJ_pQueryGlyphAttrs(FONTOBJ*,ULONG);//2
BOOL NtUserChangeClipboardChain(HWND,HWND);//2
BOOL NtGdiEngStretchBltROP(SURFOBJ*,SURFOBJ*,SURFOBJ*,CLIPOBJ*,XLATEOBJ*,COLORADJUSTMENT*,PPOINTL,LPRECTL,LPRECTL,PPOINTL,ULONG,BRUSHOBJ*,ROP4);//13
BOOL NtGdiComputeXformCoefficients(HDC);//1
HANDLE NtGdiCreateColorTransform(HDC,LPLOGCOLORSPACEW,PVOID,ULONG,PVOID,ULONG,PVOID,ULONG);//8
HANDLE NtGdiCreateColorSpace(PLOGCOLORSPACEEXW);//1
HANDLE NtGdiCreateServerMetaFile(DWORD,ULONG,PBYTE,DWORD,DWORD,DWORD);//6
DWORD NtGdiDdGetScanLine(HANDLE,OUT PDD_GETSCANLINEDATA);//2
HWND NtUserRealChildWindowFromPoint(HWND,LONG,LONG);//3
HBITMAP NtGdiCreateBitmap(INT,INT,UINT,UINT,PBYTE);//5
COLORREF NtGdiSetPixel(HDC,INT,INT,COLORREF);//4
NTSTATUS NtGdiFullscreenControl(FULLSCREENCONTROL,PVOID,DWORD,OUT PVOID,OUT PULONG);//5
BOOL NtUserDdeSetQualityOfService(HWND,PSECURITY_QUALITY_OF_SERVICE,OUT PSECURITY_QUALITY_OF_SERVICE);//3
BOOL NtGdiEngBitBlt(SURFOBJ*,SURFOBJ*,SURFOBJ*,CLIPOBJ*,XLATEOBJ*,LPRECTL,PPOINTL,PPOINTL,BRUSHOBJ*,PPOINTL,ROP4);//11
BOOL NtUserValidateRect(HWND,LPRECT);//2
BOOL NtGdiInit(VOID);//0
BOOL NtGdiGetFontResourceInfoInternalW(PWSTR,ULONG,ULONG,UINT,OUT PDWORD,PVOID,DWORD);//7
BOOL NtUserSetWindowPlacement(HWND,LPWINDOWPLACEMENT);//2
BOOL NtUserWin32PoolAllocationStats(PDWORD,SIZE_T,OUT SIZE_T*,OUT SIZE_T*,OUT PDWORD,OUT PDWORD);//6
BOOL NtGdiDwmSetHighColorMode(DXGI_FORMAT);//1
BOOL NtGdiGetTextExtent(HDC,PWSTR,INT,OUT LPSIZE,UINT);//5
INT NtGdiQueryFonts(PUNIVERSAL_FONT_ID,ULONG,OUT PLARGE_INTEGER);//3
BOOL NtGdiRemoveMergeFont(HDC,UNIVERSAL_FONT_ID*);//2
BOOL NtGdiAngleArc(HDC,INT,INT,DWORD,DWORD,DWORD);//6
INT NtGdiStretchDIBitsInternal(HDC,INT,INT,INT,INT,INT,INT,INT,INT,PBYTE,LPBITMAPINFO,DWORD,DWORD,UINT,UINT,HANDLE);//16
BOOL NtGdiPATHOBJ_bEnum(PATHOBJ*,OUT PATHDATA*);//2
NTSTATUS NtUserCtxDisplayIOCtl(ULONG,PUCHAR,ULONG);//3
HBITMAP NtGdiSetBitmapAttributes(HBITMAP,DWORD);//2
HWINSTA NtUserCreateWindowStation(POBJECT_ATTRIBUTES,ACCESS_MASK,HANDLE,DWORD,PUNICODE_STRING,UINT);//6
FD_GLYPHSET* NtGdiFONTOBJ_pfdg(FONTOBJ*);//1
HPALETTE NtUserSelectPalette(HDC,HPALETTE,BOOL);//3
BOOL NtGdiDeleteColorSpace(HANDLE);//1
DWORD NtGdiDvpGetVideoPortLine(HANDLE,OUT PDD_GETVPORTLINEDATA);//2
BOOL NtGdiRectInRegion(HRGN,OUT LPRECT);//2
BOOL NtUserUnregisterClass(PUNICODE_STRING,HINSTANCE,PCLSMENUNAME);//3
BOOL NtGdiDoBanding(HDC,BOOL,OUT PPOINTL,OUT LPSIZE);//4
ULONG_PTR NtGdiEnumFontOpen(HDC,ULONG,FLONG,ULONG,PWSTR,ULONG,OUT PULONG);//7
BOOL NtUserTrackMouseEvent(LPTRACKMOUSEEVENT);//1
NTSTATUS NtGdiPATHOBJ_vEnumStart(PATHOBJ*);//1
HBITMAP NtGdiEngCreateBitmap(SIZEL,LONG,ULONG,FLONG,PVOID);//5
DWORD NtGdiGetFontUnicodeRanges(HDC,OUT LPGLYPHSET);//2
BOOL NtUserGetCaretPos(LPPOINT);//1
SHORT NtUserGetKeyState(INT);//1
HANDLE NtGdiDdCreateMoComp(HANDLE,OUT PDD_CREATEMOCOMPDATA);//2
DWORD NtGdiDdGetAvailDriverMemory(HANDLE,OUT PDD_GETAVAILDRIVERMEMORYDATA);//2
UINT_PTR NtUserSetTimer(HWND,UINT_PTR,UINT,TIMERPROC);//4
BOOL NtUserValidateHandleSecure(HANDLE);//1
HANDLE NtGdiAddFontMemResourceEx(PVOID,DWORD,DESIGNVECTOR*,ULONG,OUT PDWORD);//5
VOID RtlInitLargeAnsiString(OUT PLARGE_ANSI_STRING,PCSZ,INT);//3
DWORD NtGdiDvpWaitForVideoPortSync(HANDLE,OUT PDD_WAITFORVPORTSYNCDATA);//2
BOOL NtGdiWidenPath(HDC);//1
BOOL NtUserSwitchDesktop(HDESK);//1
INT NtUserEnumDisplayMonitors(HDC,LPCRECT,OUT HMONITOR*,OUT LPRECT,DWORD);//5
BOOL NtGdiUnrealizeObject(HANDLE);//1
UINT NtUserMapVirtualKeyEx(UINT,UINT,DWORD,HKL);//4
BOOL NtGdiEngDeletePalette(HPALETTE);//1
DWORD NtGdiDdGetDriverState(OUT PDD_GETDRIVERSTATEDATA);//1
HCURSOR NtUserGetCursorFrameInfo(HCURSOR,DWORD,PINT,PDWORD);//4
UINT NtUserGetMenuIndex(HMENU,HMENU);//2
BOOL NtGdiSetIcmMode(HDC,ULONG,ULONG);//3
HBRUSH NtGdiSelectBrush(HDC,HBRUSH);//2
BOOL NtGdiGetTransform(HDC,DWORD,OUT LPXFORM);//3
BOOL NtGdiSTROBJ_bEnumPositionsOnly(STROBJ*,OUT PULONG,PGLYPHPOS*);//3
BOOL NtGdiRemoveFontMemResourceEx(HANDLE);//1
BOOL NtGdiDdReleaseDC(HANDLE);//1
BOOL NtGdiSetVirtualResolution(HDC,INT,INT,INT,INT);//5
LONG NtGdiGetBitmapBits(HBITMAP,ULONG,PBYTE);//3
BOOL NtUserRegisterTasklist(HWND);//1
DWORD NtGdiDvpFlipVideoPort(HANDLE,HANDLE,HANDLE,OUT PDD_FLIPVPORTDATA);//4
INT NtUserTranslateAccelerator(HWND,HACCEL,LPMSG);//3
DWORD NtGdiDvpGetVideoPortField(HANDLE,OUT PDD_GETVPORTFIELDDATA);//2
LONG NtGdiDoPalette(HGDIOBJ,WORD,WORD,PVOID,DWORD,BOOL);//6
BOOL NtGdiStartPage(HDC);//1
BOOL NtUserHideCaret(HWND);//1
INT NtGdiGetDIBitsInternal(HDC,HBITMAP,UINT,UINT,PBYTE,OUT LPBITMAPINFO,UINT,UINT,UINT);//9
BOOL NtUserGetWindowPlacement(HWND,LPWINDOWPLACEMENT);//2
HHOOK NtUserSetWindowsHookEx(HINSTANCE,PUNICODE_STRING,DWORD,INT,HOOKPROC,BOOL);//6
BOOL NtUserGetKeyboardLayoutName(PWSTR);//1
BOOL NtUserUnregisterHotKey(HWND,INT);//2
BOOL NtUserThunkedMenuInfo(HMENU,LPCMENUINFO);//2
DWORD NtUserGetMouseMovePointsEx(UINT,LPMOUSEMOVEPOINT,LPMOUSEMOVEPOINT,INT,DWORD);//5
BOOL NtUserWaitMessage(VOID);//0
BOOL NtGdiEnumFontChunk(HDC,ULONG_PTR,ULONG,OUT PULONG,OUT PENUMFONTDATAW);//5
BOOL NtGdiPtInRegion(HRGN,INT,INT);//3
DWORD NtGdiDdAlphaBlt(HANDLE,HANDLE,OUT PDD_BLTDATA);//3
BOOL NtGdiBeginPath(HDC);//1
HDWP NtUserDeferWindowPos(HDWP,HWND,HWND,INT,INT,INT,INT,UINT);//8
DWORD NtUserGetKeyboardType(DWORD);//1
BOOL NtGdiScaleViewportExtEx(HDC,INT,INT,INT,INT,OUT LPSIZE);//6
HKL NtUserLoadKeyboardLayoutEx(HANDLE,DWORD,PUNICODE_STRING,HKL,PUNICODE_STRING,DWORD,UINT);//7
DWORD NtGdiDvpGetVideoSignalStatus(HANDLE,OUT PDD_GETVPORTSIGNALDATA);//2
BOOL NtUserDefSetText(HWND,PLARGE_STRING);//2
INT NtGdiOffsetClipRgn(HDC,INT,INT);//3
PATHOBJ* NtGdiCLIPOBJ_ppoGetPath(CLIPOBJ*);//1
BOOL NtGdiEndPage(HDC);//1
DWORD NtUserRemoteStopScreenUpdates(VOID);//0
BOOL NtUserCallMsgFilter(LPMSG,INT);//2
BOOL NtGdiAbortPath(HDC);//1
DWORD NtGdiD3dDrawPrimitives2(HANDLE,HANDLE,OUT LPD3DNTHAL_DRAWPRIMITIVES2DATA,OUT FLATPTR*,OUT PDWORD,OUT FLATPTR*,OUT PDWORD);//7
BOOL NtGdiEngMarkBandingSurface(HSURF);//1
BOOL NtGdiAnyLinkedFonts(VOID);//0
BOOL NtGdiSetTextJustification(HDC,INT,INT);//3
DWORD NtGdiDdUnlockD3D(HANDLE,OUT PDD_UNLOCKDATA);//2
BOOL NtGdiEngTextOut(SURFOBJ*,STROBJ*,FONTOBJ*,CLIPOBJ*,LPRECTL,LPRECTL,BRUSHOBJ*,BRUSHOBJ*,PPOINTL,MIX);//10
BOOL NtUserQueryUserCounters(DWORD,PVOID,DWORD,OUT PVOID,DWORD);//5
BOOL NtGdiSfmRegisterLogicalSurfaceForSignaling(HLSURF,BOOL);//2
BOOL NtGdiEngCheckAbort(SURFOBJ*);//1
DWORD NtGdiDvpUpdateVideoPort(HANDLE,HANDLE*,HANDLE*,OUT PDD_UPDATEVPORTDATA);//4
HBITMAP NtGdiCreateBitmapFromDxSurface2(HDC,UINT,UINT,DWORD,DWORD,BOOL,HANDLE);//7
ULONG NtGdiMakeFontDir(FLONG,PBYTE,UINT,PWSTR,UINT);//5
BOOL NtGdiCombineTransform(OUT LPXFORM,LPXFORM,LPXFORM);//3
BOOL NtGdiTransformPoints(HDC,LPPOINT,LPPOINT,INT,INT);//5
DWORD NtUserDdeInitialize(OUT PHANDLE,OUT HWND*,OUT PDWORD,DWORD,PVOID);//5
BOOL NtGdiExtTextOutW(HDC,INT,INT,UINT,LPRECT,PWSTR,INT,PINT,DWORD);//9
HRGN NtGdiCreateEllipticRgn(INT,INT,INT,INT);//4
HDC NtUserGetWindowDC(HWND);//1
DWORD NtGdiDdEndMoCompFrame(HANDLE,OUT PDD_ENDMOCOMPFRAMEDATA);//2
FD_GLYPHSET* NtGdiEngComputeGlyphSet(INT,INT,INT);//3
BOOL NtUserGetScrollBarInfo(HWND,LONG,PSCROLLBARINFO);//3
DWORD NtGdiGetFontFileData(UINT,UINT,PULONGLONG,PVOID,SIZE_T);//5
HBITMAP NtGdiGetObjectBitmapHandle(HBRUSH,OUT PUINT);//2
BOOL NtUserDrawIconEx(HDC,INT,INT,HICON,INT,INT,UINT,HBRUSH,UINT,BOOL,PVOID);//11
DWORD NtGdiGetGlyphIndicesW(HDC,PCWSTR,INT,PWORD,DWORD);//5
DWORD NtUserYieldTask(VOID);//0
BOOL NtUserLockWorkStation(VOID);//0
BOOL NtGdiRoundRect(HDC,INT,INT,INT,INT,INT,INT);//7
BOOL NtUserImpersonateDdeClientWindow(HWND,HWND);//2
INT NtGdiGetDeviceCaps(HDC,INT);//2
DWORD NtUserDrawMenuBarTemp(HWND,HDC,PRECT,HMENU,HFONT);//5
UINT NtGdiGetNearestPaletteIndex(HPALETTE,COLORREF);//2
INT NtGdiDrawEscape(HDC,INT,INT,PSTR);//4
NTSTATUS NtUserTestForInteractiveUser(PLUID);//1
BOOL NtUserBlockInput(BOOL);//1
BOOL NtUserSetProp(HWND,ATOM,HANDLE);//3
BOOL NtUserSetMenuFlagRtoL(HMENU);//1
BOOL NtGdiSetFontXform(HDC,DWORD,DWORD);//3
BOOL NtGdiEngStretchBlt(SURFOBJ*,SURFOBJ*,SURFOBJ*,CLIPOBJ*,XLATEOBJ*,COLORADJUSTMENT*,PPOINTL,LPRECTL,LPRECTL,PPOINTL,ULONG);//11
ULONG NtGdiXFORMOBJ_iGetXform(XFORMOBJ*,OUT XFORML*);//2
DWORD NtUserGetRawInputDeviceList(PRAWINPUTDEVICELIST,PUINT,UINT);//3
HANDLE NtGdiBRUSHOBJ_hGetColorTransform(BRUSHOBJ*);//1
BOOL NtUserMoveWindow(HWND,INT,INT,INT,INT,BOOL);//6
BOOL NtUserUnhookWindowsHookEx(HHOOK);//1
DWORD NtUserGetRawInputData(HRAWINPUT,UINT,PVOID,PUINT,UINT);//5
BOOL NtUserOpenClipboard(HWND,OUT PBOOL);//2
BOOL NtGdiGetDCDword(HDC,UINT,OUT PDWORD);//3
HKL NtUserGetKeyboardLayout(DWORD);//1
BOOL NtGdiEnumFontClose(ULONG_PTR);//1
BOOL NtUserPaintDesktop(HDC);//1
DWORD NtGdiDvpGetVideoPortBandwidth(HANDLE,OUT PDD_GETVPORTBANDWIDTHDATA);//2
BOOL NtUserShowWindowAsync(HWND,LONG);//2
NTSTATUS NtUserProcessConnect(HANDLE,OUT PUSERCONNECT,ULONG);//3
BOOL NtUserSetSysColors(INT,PINT,LPCOLORREF,FLONG);//4
BOOL NtGdiPlgBlt(HDC,LPPOINT,HDC,INT,INT,INT,INT,HBITMAP,INT,INT,DWORD);//11
BOOL NtGdiFontIsLinked(HDC);//1
BOOL NtUserUserHandleGrantAccess(HANDLE,HANDLE,BOOL);//3
HBRUSH NtGdiCreatePatternBrushInternal(HBITMAP,BOOL,BOOL);//3
HFONT NtGdiSelectFont(HDC,HFONT);//2
HRGN NtGdiCreateRectRgn(INT,INT,INT,INT);//4
DWORD NtGdiDvpGetVideoPortFlipStatus(HANDLE,OUT PDD_GETVPORTFLIPSTATUSDATA);//2
BOOL NtUserSetThreadDesktop(HDESK);//1
VOID NtUserNotifyWinEvent(DWORD,HWND,LONG,LONG);//4
BOOL NtUserLockWindowStation(HWINSTA);//1
BOOL NtUserRemoveMenu(HMENU,UINT,UINT);//3
INT NtGdiAddFontResourceW(PWCHAR,ULONG,ULONG,FLONG,DWORD,DESIGNVECTOR*);//6
DWORD NtUserGetRawInputBuffer(PRAWINPUT,PUINT,UINT);//3
BOOL NtUserDestroyMenu(HMENU);//1
HHOOK NtUserSetWindowsHookAW(INT,HOOKPROC,BOOL);//3
INT NtGdiSaveDC(HDC);//1
BOOL NtGdiGetTextExtentExW(HDC,PWSTR,ULONG,ULONG,OUT PULONG,PULONG,OUT LPSIZE,FLONG);//8
DWORD NtUserMNDragLeave(VOID);//0
BOOL NtGdiGetETM(HDC,OUT EXTTEXTMETRIC*);//2
HANDLE NtGdiCreateClientObj(ULONG);//1
BOOL NtUserGetObjectInformation(HANDLE,DWORD,PVOID,DWORD,PDWORD);//5
BOOL NtUserCreateCaret(HWND,HBITMAP,INT,INT);//4
BOOL NtGdiGetMiterLimit(HDC,OUT PDWORD);//2
BOOL NtGdiSTROBJ_bEnum(STROBJ*,OUT PULONG,PGLYPHPOS*);//3
BOOL NtGdiDeleteColorTransform(HDC,HANDLE);//2
HWND NtUserGetClipboardOwner(VOID);//0
BOOL NtGdiPatBlt(HDC,INT,INT,INT,INT,DWORD);//6
HBITMAP NtGdiEngCreateDeviceBitmap(DHSURF,SIZEL,ULONG);//3
BOOL NtGdiSetPixelFormat(HDC,INT);//2
DWORD NtGdiGetFontFileInfo(UINT,UINT,PFONT_FILE_INFO,SIZE_T,OUT PSIZE_T);//5
BOOL NtUserPrintWindow(HWND,HDC,UINT);//3
ULONG NtGdiEnumObjects(HDC,INT,ULONG,PVOID);//4
BOOL NtUserGetUpdateRect(HWND,LPRECT,BOOL);//3
BOOL NtUserShowCaret(HWND);//1
PVOID NtGdiFONTOBJ_pvTrueTypeFontFile(FONTOBJ*,OUT PULONG);//2
BOOL NtGdiGetRasterizerCaps(LPRASTERIZER_STATUS,ULONG);//2
DWORD NtGdiDdDestroyD3DBuffer(HANDLE);//1
INT NtGdiSetDIBitsToDeviceInternal(HDC,INT,INT,DWORD,DWORD,INT,INT,DWORD,DWORD,PBYTE,LPBITMAPINFO,DWORD,UINT,UINT,BOOL,HANDLE);//16
HANDLE NtUserRemoveProp(HWND,ATOM);//2
BOOL NtGdiGetCharABCWidthsW(HDC,UINT,ULONG,PWCHAR,FLONG,PVOID);//6
LRESULT NtUserCallNextHookEx(INT,WPARAM,LPARAM,BOOL);//4
BOOL NtUserDeleteMenu(HMENU,UINT,UINT);//3
DWORD NtGdiDdCreateSurface(HANDLE,HANDLE*,OUT DDSURFACEDESC*,OUT DD_SURFACE_GLOBAL*,OUT DD_SURFACE_LOCAL*,OUT DD_SURFACE_MORE*,OUT DD_CREATESURFACEDATA*,OUT HANDLE*);//8
UINT NtUserRegisterWindowMessage(PUNICODE_STRING);//1
DWORD NtUserSetImeInfoEx(PIMEINFOEX);//1
BOOL NtGdiXFORMOBJ_bApplyXform(XFORMOBJ*,ULONG,ULONG,PPOINTL,PPOINTL);//5
BOOL NtGdiDdResetVisrgn(HANDLE,HWND);//2
BOOL NtUserInvalidateRgn(HWND,HRGN,BOOL);//3
LONG_PTR NtUserSetClassLongPtr(HWND,INT,LONG_PTR,BOOL);//4
ULONG NtGdiXLATEOBJ_iXlate(XLATEOBJ*,ULONG);//2
BOOL NtGdiGetMonitorID(HDC,DWORD,PWSTR);//3
ULONG NtGdiBRUSHOBJ_ulGetBrushColor(BRUSHOBJ*);//1
HMENU NtUserGetSystemMenu(HWND,BOOL);//2
SURFOBJ* NtGdiEngLockSurface(HSURF);//1
BOOL NtGdiPolyPatBlt(HDC,DWORD,PPOLYPATBLT,DWORD,DWORD);//5
UINT NtGdiGetStringBitmapW(HDC,PWSTR,UINT,PBYTE,UINT);//5
BOOL NtUserSetObjectInformation(HANDLE,DWORD,PVOID,DWORD);//4
BOOL NtUserHiliteMenuItem(HWND,HMENU,UINT,UINT);//4
DWORD NtUserDbgWin32HeapStat(PDBGHEAPSTAT,DWORD);//2
BOOL NtUserDdeGetQualityOfService(HWND,HWND,OUT PSECURITY_QUALITY_OF_SERVICE);//3
BOOL NtGdiSetMiterLimit(HDC,DWORD,OUT PDWORD);//3
DWORD NtGdiDdCreateSurfaceEx(HANDLE,HANDLE,DWORD);//3
HDC NtGdiCreateMetafileDC(HDC);//1
NTSTATUS NtGdiEngUnlockSurface(SURFOBJ*);//1
BOOL NtGdiSetPUMPDOBJ(HUMPD,BOOL,OUT HUMPD*,OUT PBOOL);//4
BOOL NtGdiGetWidthTable(HDC,ULONG,PWCHAR,ULONG,PUSHORT,OUT WIDTHDATA*,OUT FLONG*);//7
BOOLEAN NtUserDestroyWindow(HWND);//1
NTSTATUS NtUserBuildNameList(HWINSTA,ULONG,PVOID,PULONG);//4
BOOL NtGdiFrameRgn(HDC,HRGN,HBRUSH,INT,INT);//5
BOOL NtUserGetClassInfo(HINSTANCE,PUNICODE_STRING,LPWNDCLASSEXW,PWSTR*,BOOL);//5
INT NtUserToUnicodeEx(UINT,UINT,PBYTE,PWSTR,INT,UINT,HKL);//7
BOOL NtUserSetWindowStationUser(HWINSTA,PLUID,PSID,DWORD);//4
DWORD NtGdiDdFlip(HANDLE,HANDLE,HANDLE,HANDLE,OUT PDD_FLIPDATA);//5
BOOL NtGdiMakeObjectUnXferable(HANDLE);//1
NTSTATUS NtGdiSTROBJ_vEnumStart(OUT STROBJ*);//1
DWORD NtGdiDxgGenericThunk(ULONG_PTR,ULONG_PTR,OUT SIZE_T*,OUT PVOID,OUT SIZE_T*,OUT PVOID);//6
DWORD NtUserDragObject(HWND,HWND,UINT,DWORD,HCURSOR);//5
NTSTATUS NtUserQueryInformationThread(HANDLE,USERTHREADINFOCLASS,OUT PVOID,ULONG);//4
BOOL NtGdiEngTransparentBlt(SURFOBJ*,SURFOBJ*,CLIPOBJ*,XLATEOBJ*,LPRECTL,LPRECTL,ULONG,ULONG);//8
BOOL NtUserGetIconInfo(HANDLE,OUT PICONINFO,OUT PUNICODE_STRING,OUT PUNICODE_STRING,OUT PDWORD,BOOL);//6
DWORD NtGdiDdUpdateOverlay(HANDLE,HANDLE,OUT PDD_UPDATEOVERLAYDATA);//3
BOOL NtUserSetSystemMenu(HWND,HMENU);//2
BOOL NtGdiConsoleTextOut(HDC,POLYTEXTW*,UINT,LPRECTL);//4
ULONG NtGdiGetPerBandInfo(HDC,OUT PERBANDINFO*);//2
BOOL NtUserGetGUIThreadInfo(DWORD,LPGUITHREADINFO);//2
HDC NtGdiCreateCompatibleDC(HDC);//1
HFONT NtGdiHfontCreate(ENUMLOGFONTEXDVW*,ULONG,LFTYPE,FLONG,PVOID);//5
ULONG NtGdiGetKerningPairs(HDC,ULONG,KERNINGPAIR*);//3
BOOL NtGdiGetUFI(HDC,OUT PUNIVERSAL_FONT_ID,OUT DESIGNVECTOR*,OUT PULONG,OUT PULONG,OUT FLONG*);//6
DWORD NtUserEvent(PEVENT_PACKET);//1
BOOL NtGdiSTROBJ_bGetAdvanceWidths(STROBJ*,ULONG,ULONG,POINTQF*);//4
INT NtGdiDescribePixelFormat(HDC,INT,UINT,PPIXELFORMATDESCRIPTOR);//4
DWORD NtGdiDvpDestroyVideoPort(HANDLE,OUT PDD_DESTROYVPORTDATA);//2
BOOL NtUserDrawAnimatedRects(HWND,INT,LPRECT,LPRECT);//4
HWND NtUserSetClipboardViewer(HWND);//1
BOOL NtGdiEnumFonts(HDC,ULONG,FLONG,ULONG,PCWSTR,ULONG,OUT PULONG,PVOID);//8
BOOL NtGdiEllipse(HDC,INT,INT,INT,INT);//5
LONG NtGdiSetBitmapBits(HBITMAP,ULONG,PBYTE);//3
DWORD NtUserGetClipboardSequenceNumber(VOID);//0
BOOL NtGdiEngGradientFill(SURFOBJ*,CLIPOBJ*,XLATEOBJ*,TRIVERTEX*,ULONG,PVOID,ULONG,LPRECTL,PPOINTL,ULONG);//10
HDESK NtUserOpenDesktop(POBJECT_ATTRIBUTES,DWORD,ACCESS_MASK);//3
BOOL NtUserScrollDC(HDC,INT,INT,LPRECT,LPRECT,HRGN,LPRECT);//7
NTSTATUS NtUserRemoteRedrawRectangle(WORD,WORD,WORD,WORD);//4
ULONG NtGdiFONTOBJ_cGetGlyphs(FONTOBJ*,ULONG,ULONG,HGLYPH*,PVOID*);//5
ULONG_PTR NtGdiPolyPolyDraw(HDC,LPPOINT,PULONG,ULONG,INT);//5
BOOL NtUserGetLayeredWindowAttributes(HWND,LPCOLORREF,PBYTE,PDWORD);//4
BOOL NtGdiUnmapMemFont(PVOID);//1
BOOL NtGdiUMPDEngFreeUserMem(KERNEL_PVOID*);//1
ULONG_PTR NtGdiGetColorSpaceforBitmap(HBITMAP);//1
PVOID NtGdiBRUSHOBJ_pvAllocRbrush(BRUSHOBJ*,ULONG);//2
NTSTATUS NtUserInitialize(DWORD,HANDLE,HANDLE);//3
DWORD NtGdiDdWaitForVerticalBlank(HANDLE,OUT PDD_WAITFORVERTICALBLANKDATA);//2
BOOL NtUserGetMenuItemRect(HWND,HMENU,UINT,LPRECT);//4
BOOL NtUserSetProcessWindowStation(HWINSTA);//1
DWORD NtGdiDdCreateD3DBuffer(HANDLE,OUT HANDLE*,OUT DDSURFACEDESC*,OUT DD_SURFACE_GLOBAL*,OUT DD_SURFACE_LOCAL*,OUT DD_SURFACE_MORE*,OUT DD_CREATESURFACEDATA*,OUT HANDLE*);//8
INT NtUserGetUpdateRgn(HWND,HRGN,BOOL);//3
HWINSTA NtUserGetProcessWindowStation(VOID);//0
BOOL NtGdiLineTo(HDC,INT,INT);//3
BOOL NtGdiRestoreDC(HDC,INT);//2
BOOL NtGdiRectVisible(HDC,LPRECT);//2
INT NtUserSetWindowRgn(HWND,HRGN,BOOL);//3
ULONG NtGdiColorCorrectPalette(HDC,HPALETTE,ULONG,ULONG,PALETTEENTRY*,ULONG);//6
HICON NtUserFindExistingCursorIcon(PUNICODE_STRING,PUNICODE_STRING,FINDEXISTINGCURICONPARAM*);//3
BOOL NtUserRegisterRawInputDevices(PCRAWINPUTDEVICE,UINT,UINT);//3
BOOL NtGdiGetCharWidthInfo(HDC,OUT PCHWIDTHINFO);//2
BOOL NtGdiBRUSHOBJ_DeleteRbrush(BRUSHOBJ*,BRUSHOBJ*);//2
HBITMAP NtGdiClearBitmapAttributes(HBITMAP,DWORD);//2
BOOL NtUserSetCursorIconData(HCURSOR,PUNICODE_STRING,PUNICODE_STRING,CURSORDATA*);//4
BOOL NtGdiScaleWindowExtEx(HDC,INT,INT,INT,INT,OUT LPSIZE);//6
HANDLE NtGdiDdCreateSurfaceObject(HANDLE,HANDLE,PDD_SURFACE_LOCAL,PDD_SURFACE_MORE,PDD_SURFACE_GLOBAL,BOOL);//6
CLIPOBJ* NtGdiEngCreateClip(VOID);//0
BOOL NtGdiRectangle(HDC,INT,INT,INT,INT);//5
NTSTATUS NtGdiDdDestroyFullscreenSprite(HDC,HANDLE);//2
HANDLE NtUserConvertMemHandle(PVOID,DWORD);//2
BOOL NtGdiEnableEudc(BOOL);//1
BOOL NtUserDragDetect(HWND,POINT);//2
BOOL NtUserPeekMessage(LPMSG,HWND,UINT,UINT,UINT);//5
INT NtGdiOffsetRgn(HRGN,INT,INT);//3
BOOL NtUserSetShellWindowEx(HWND,HWND);//2
BOOL NtGdiArcInternal(ARCTYPE,HDC,INT,INT,INT,INT,INT,INT,INT,INT);//10
VOID NtUserSetDbgTag(INT,DWORD);//2
DWORD NtUserCallHwndParam(HWND,DWORD,DWORD);//3
HDC NtUserGetDC(HWND);//1
BOOL NtUserEndMenu(VOID);//0
HBRUSH NtGdiClearBrushAttributes(HBRUSH,DWORD);//2
HCURSOR NtUserSetCursor(HCURSOR);//1
ULONG NtGdiGetEmbedFonts(VOID);//0
NTSTATUS NtUserInitTask(UINT,DWORD,PUNICODE_STRING,PUNICODE_STRING,DWORD,DWORD,DWORD,DWORD,DWORD,DWORD,DWORD);//11
INT NtUserInternalGetWindowText(HWND,PWSTR,INT);//3
NTSTATUS NtGdiDdCreateFullscreenSprite(HDC,COLORREF,OUT HANDLE*,OUT HDC*);//4
BOOL NtGdiTileBitBlt(HDC,LPRECTL,HDC,LPRECTL,PPOINTL,DWORD,DWORD);//7
BOOL NtGdiEngAssociateSurface(HSURF,HDEV,FLONG);//3
HRGN NtGdiExtCreateRegion(LPXFORM,DWORD,LPRGNDATA);//3
VOID NtUserDbgWin32HeapFail(DWORD,BOOL);//2
BOOL NtGdiEngLineTo(SURFOBJ*,CLIPOBJ*,BRUSHOBJ*,LONG,LONG,LONG,LONG,LPRECTL,MIX);//9
INT NtGdiCombineRgn(HRGN,HRGN,HRGN,INT);//4
BOOL NtUserSetWindowFNID(HWND,WORD);//2
INT NtGdiStartDoc(HDC,DOCINFOW*,OUT PBOOL,INT);//4
DWORD NtGdiDdCanCreateD3DBuffer(HANDLE,OUT PDD_CANCREATESURFACEDATA);//2
BOOL NtGdiMakeInfoDC(HDC,BOOL);//2
BOOL NtUserIsClipboardFormatAvailable(UINT);//1
BOOL NtGdiPolyTextOutW(HDC,POLYTEXTW*,UINT,DWORD);//4
HWND NtUserGetAncestor(HWND,UINT);//2
ULONG_PTR NtUserGetCPD(HWND,GETCPD,ULONG_PTR);//3
HWINSTA NtUserOpenWindowStation(POBJECT_ATTRIBUTES,ACCESS_MASK);//2
BOOL NtGdiResizePalette(HPALETTE,UINT);//2
HDESK NtUserCreateDesktop(POBJECT_ATTRIBUTES,PUNICODE_STRING,LPDEVMODEW,DWORD,ACCESS_MASK);//5
PCLS NtUserGetWOWClass(HINSTANCE,PUNICODE_STRING);//2
BOOL NtGdiSelectClipPath(HDC,INT);//2
HANDLE NtGdiGetDCObject(HDC,INT);//2
DWORD NtGdiSTROBJ_dwGetCodePage(STROBJ*);//1
BOOL NtGdiPolyDraw(HDC,LPPOINT,PBYTE,ULONG);//4
DWORD NtUserGetListBoxInfo(HWND);//1
BOOL NtUserNotifyProcessCreate(DWORD,DWORD,ULONG_PTR,DWORD);//4
HWINEVENTHOOK NtUserSetWinEventHook(UINT,UINT,HMODULE,PUNICODE_STRING,WINEVENTPROC,DWORD,DWORD,UINT);//8
BOOL NtGdiAddEmbFontToDC(HDC,PVOID*);//2
HWND NtUserChildWindowFromPointEx(HWND,POINT,UINT);//3
BOOL NtUserBitBltSysBmp(HDC,INT,INT,INT,INT,INT,INT,DWORD);//8
DWORD NtGdiGetPixel(HDC,INT,INT);//3
DWORD NtGdiDdGetDriverInfo(HANDLE,OUT PDD_GETDRIVERINFODATA);//2
BOOL NtUserGetKeyboardState(OUT PBYTE);//1
XFORMOBJ* NtGdiFONTOBJ_pxoGetXform(FONTOBJ*);//1
HBITMAP NtGdiCreateCompatibleBitmap(HDC,INT,INT);//3
BOOL NtUserFlashWindowEx(PFLASHWINFO);//1
ULONG NtGdiGetOutlineTextMetricsInternalW(HDC,ULONG,OUTLINETEXTMETRICW*,OUT TMDIFF*);//4
BOOL NtGdiUnloadPrinterDriver(PWSTR,ULONG);//2
BOOL NtGdiDrawStream(HDC,ULONG,PVOID);//3
BOOL NtGdiSetLinkedUFIs(HDC,PUNIVERSAL_FONT_ID,ULONG);//3
BOOL NtUserKillTimer(HWND,UINT_PTR);//2
ULONG NtGdiFONTOBJ_cGetAllGlyphHandles(FONTOBJ*,OUT HGLYPH*);//2
BOOL NtUserGetMonitorInfo(HMONITOR,OUT LPMONITORINFO);//2
BOOL NtGdiBeginGdiRendering(HBITMAP,BOOL,PVOID);//3
BOOL NtUserGetAltTabInfo(HWND,INT,PALTTABINFO,PWSTR,UINT,BOOL);//6
HANDLE NtGdiXLATEOBJ_hGetColorTransform(XLATEOBJ*);//1
DWORD NtGdiD3dContextDestroy(LPD3DNTHAL_CONTEXTDESTROYDATA);//1
BOOL NtGdiCLIPOBJ_bEnum(CLIPOBJ*,ULONG,PULONG);//3
BOOL NtGdiInitSpool(VOID);//0
NTSTATUS NtUserResolveDesktopForWOW(OUT PUNICODE_STRING);//1
VOID NtUserSetThreadState(DWORD,DWORD);//2
BOOL NtGdiEndDoc(HDC);//1
BOOL NtGdiDdReenableDirectDrawObject(HANDLE,OUT PBOOL);//2
BOOL NtUserSetMenuContextHelpId(HMENU,DWORD);//2
INT NtGdiGetTextCharsetInfo(HDC,OUT LPFONTSIGNATURE,DWORD);//3
HANDLE NtGdiDdCreateDirectDrawObject(HDC);//1
INT NtGdiGetLinkedUFIs(HDC,PUNIVERSAL_FONT_ID,INT);//3
NTSTATUS NtUserConsoleControl(CONSOLECONTROL,PVOID,ULONG);//3
NTSTATUS NtGdiGetStats(HANDLE,INT,INT,PVOID,UINT);//5
BOOL NtUserSetLayeredWindowAttributes(HWND,COLORREF,BYTE,DWORD);//4
HPALETTE NtGdiEngCreatePalette(ULONG,ULONG,PULONG,FLONG,FLONG,FLONG);//6
BOOL NtGdiGetTextMetricsW(HDC,TMW_INTERNAL*,ULONG);//3
HWND NtUserSetCapture(HWND);//1
BOOL NtUserEmptyClipboard(VOID);//0
HWND NtUserFindWindowEx(HWND,HWND,PUNICODE_STRING,PUNICODE_STRING,DWORD);//5
DWORD NtUserGetRegisteredRawInputDevices(PRAWINPUTDEVICE,PUINT,UINT);//3
DWORD NtUserQueryWindow(HWND,DWORD);//2
VOID RtlInitLargeUnicodeString(OUT PLARGE_UNICODE_STRING,PCWSTR,INT);//3
UINT_PTR NtUserSetSystemTimer(HWND,UINT_PTR,UINT,TIMERPROC);//4
BOOL NtUserGetClipCursor(LPRECT);//1
DWORD NtGdiDdRenderMoComp(HANDLE,OUT PDD_RENDERMOCOMPDATA);//2
INT NtGdiGetPath(HDC,LPPOINT,PBYTE,INT);//4
WORD NtUserSetWindowWord(HWND,INT,WORD);//3
NTSTATUS NtGdiPATHOBJ_vGetBounds(PATHOBJ*,OUT PRECTFX);//2
BOOL NtGdiEngFillPath(SURFOBJ*,PATHOBJ*,CLIPOBJ*,BRUSHOBJ*,PPOINTL,MIX,FLONG);//7
ULONG NtGdiQueryFontAssocInfo(HDC);//1
DWORD NtGdiD3dContextDestroyAll(OUT LPD3DNTHAL_CONTEXTDESTROYALLDATA);//1
BOOL NtGdiEngStrokeAndFillPath(SURFOBJ*,PATHOBJ*,CLIPOBJ*,XFORMOBJ*,BRUSHOBJ*,LINEATTRS*,BRUSHOBJ*,PPOINTL,MIX,FLONG);//10
LONG NtGdiHT_Get8BPPFormatPalette(OUT LPPALETTEENTRY,USHORT,USHORT,USHORT);//4
DWORD NtGdiDvpAcquireNotification(HANDLE,OUT HANDLE*,LPDDVIDEOPORTNOTIFY);//3
BOOL NtUserRegisterHotKey(HWND,INT,UINT,UINT);//4
DWORD NtUserMinMaximize(HWND,UINT,BOOL);//3
RTL_ATOM NtUserRegisterClassExWOW(LPWNDCLASSEXW,PUNICODE_STRING,PUNICODE_STRING,PCLSMENUNAME,DWORD,DWORD,PDWORD);//7
BOOL NtUserClipCursor(LPRECT);//1
NTSTATUS NtUserInitializeClientPfnArrays(PPFNCLIENT,PPFNCLIENT,PPFNCLIENTWORKER,HINSTANCE);//4
UINT NtUserEnableMenuItem(HMENU,UINT,UINT);//3
HBRUSH NtGdiSetBrushAttributes(HBRUSH,DWORD);//2
BOOL NtGdiDdDeleteSurfaceObject(HANDLE);//1
BOOL NtUserAttachThreadInput(DWORD,DWORD,BOOL);//3
BOOL NtUserEndDeferWindowPosEx(HDWP,BOOL);//2
BOOL NtGdiFlattenPath(HDC);//1
NTSTATUS NtUserEnumDisplaySettings(PUNICODE_STRING,DWORD,LPDEVMODEW,DWORD);//4
DWORD NtGdiDdColorControl(HANDLE,OUT PDD_COLORCONTROLDATA);//2
BOOL NtUserRealInternalGetMessage(LPMSG,HWND,UINT,UINT,UINT,BOOL);//6
BOOLEAN NtUserGetTitleBarInfo(HWND,PTITLEBARINFO);//2
INT NtUserGetClipboardFormatName(UINT,PWSTR,INT);//3
BOOL NtUserCloseClipboard(VOID);//0
HDESK NtUserGetThreadDesktop(DWORD,HDESK);//2
NTSTATUS NtGdiFONTOBJ_vGetInfo(FONTOBJ*,ULONG,FONTINFO*);//3
HRGN NtGdiCreateRoundRectRgn(INT,INT,INT,INT,INT,INT);//6
HWND NtUserGetClipboardViewer(VOID);//0
BOOL NtGdiEngDeleteSurface(HSURF);//1
BOOL NtUserPostMessage(HWND,UINT,WPARAM,LPARAM);//4
DWORD NtUserSetScrollInfo(HWND,INT,LPCSCROLLINFO,BOOL);//4
ULONG NtGdiCLIPOBJ_cEnumStart(CLIPOBJ*,BOOL,ULONG,ULONG,ULONG);//5
BOOL NtGdiDdSetGammaRamp(HANDLE,HDC,PVOID);//3
ULONG NtGdiGetServerMetaFileBits(HANDLE,ULONG,PBYTE,OUT PDWORD,OUT PDWORD,OUT PDWORD,OUT PDWORD);//7
UINT NtGdiGetSystemPaletteUse(HDC);//1
BOOL NtGdiGetDeviceGammaRamp(HDC,PVOID);//2
DWORD NtGdiDdChangeSurfacePointer(HANDLE,PVOID);//2
DWORD NtGdiDdAddAttachedSurface(HANDLE,HANDLE,OUT PDD_ADDATTACHEDSURFACEDATA);//3
BOOL NtGdiAlphaBlend(HDC,LONG,LONG,LONG,LONG,HDC,LONG,LONG,LONG,LONG,BLENDFUNCTION,HANDLE);//12
ULONG NtGdiGetFontData(HDC,DWORD,DWORD,PVOID,ULONG);//5
NTSTATUS NtUserRemoteConnect(PDOCONNECTDATA,ULONG,PWCHAR);//3
BOOL NtUserSoundSentry(VOID);//0
BOOL NtUserGetMessage(LPMSG,HWND,UINT,UINT);//4
BOOL NtGdiMonoBitmap(HBITMAP);//1
HDC NtUserGetDCEx(HWND,HANDLE,ULONG);//3
LONG_PTR NtUserSetWindowLongPtr(HWND,INT,LONG_PTR,BOOL);//4
DWORD NtUserGetRawInputDeviceInfo(HANDLE,UINT,PVOID,PUINT);//4
DWORD NtUserCallHwndParamLock(HWND,DWORD,DWORD);//3
BOOL NtGdiModifyWorldTransform(HDC,LPXFORM,DWORD);//3
ULONG NtGdiGetEudcTimeStampEx(PWSTR,ULONG,BOOL);//3
DWORD NtGdiDdDestroySurface(HANDLE,BOOL);//2
HDC NtGdiDdGetDC(HANDLE,PALETTEENTRY*);//2
DWORD NtGdiGetGlyphIndicesWInternal(HDC,PWSTR,INT,PWORD,DWORD,BOOL);//6
HSURF NtGdiEngCreateDeviceSurface(DHSURF,SIZEL,ULONG);//3
DWORD NtUserCountClipboardFormats(VOID);//0
BOOL NtUserLockWindowUpdate(HWND);//1
HMONITOR NtUserMonitorFromWindow(HWND,DWORD);//2
BOOL NtGdiHLSurfSetInformation(HLSURF,HLSURF_INFORMATION_CLASS,PVOID,ULONG);//4
BOOL NtUserCallHwndLock(HWND,DWORD);//2
DWORD NtUserAlterWindowStyle(HWND,DWORD,LONG);//3
DWORD NtUserGetGuiResources(HANDLE,DWORD);//2
ULONG NtGdiGetRegionData(HRGN,ULONG,LPRGNDATA);//3
NTSTATUS NtUserSetInformationProcess(HANDLE,USERPROCESSINFOCLASS,PVOID,ULONG);//4
BOOL NtGdiEngStrokePath(SURFOBJ*,PATHOBJ*,CLIPOBJ*,XFORMOBJ*,BRUSHOBJ*,PPOINTL,LINEATTRS*,MIX);//8
DWORD NtGdiDdSetColorKey(HANDLE,OUT PDD_SETCOLORKEYDATA);//2
HWND NtUserCreateWindowEx(DWORD,PLARGE_STRING,PLARGE_STRING,PLARGE_STRING,DWORD,INT,INT,INT,INT,HWND,HMENU,HINSTANCE,PVOID,DWORD,PVOID);//15
BOOL NtUserSetScrollBarInfo(HWND,LONG,SETSCROLLBARINFO*);//3
BOOL NtGdiCloseFigure(HDC);//1
BOOL NtGdiEngPaint(SURFOBJ*,CLIPOBJ*,BRUSHOBJ*,PPOINTL,MIX);//5
DWORD NtUserGetKeyNameText(LONG,PWSTR,INT);//3
INT NtGdiSetupPublicCFONT(HDC,HFONT,ULONG);//3
BOOL NtGdiGetDeviceCapsAll(HDC,OUT PDEVCAPS);//2
DWORD NtGdiSetLayout(HDC,LONG,DWORD);//3
BOOLEAN NtUserDestroyAcceleratorTable(HACCEL);//1
NTSTATUS NtGdiGetCurrentDpiInfo(HMONITOR,OUT PVOID);//2
HANDLE NtUserGetClipboardData(UINT,PGETCLIPBDATA);//2
HBRUSH NtUserGetControlBrush(HWND,HDC,UINT);//3
BOOL RtlLargeStringToUnicodeString(PUNICODE_STRING,PLARGE_STRING);//2
DWORD NtUserWaitForInputIdle(ULONG_PTR,DWORD,BOOL);//3
UINT NtUserGetCaretBlinkTime(VOID);//0
BOOL NtGdiAbortDoc(HDC);//1
DWORD NtUserVkKeyScanEx(WCHAR,HKL,BOOL);//3
BOOL NtGdiSetBitmapDimension(HBITMAP,INT,INT,LPSIZE);//4
BOOL NtUserTrackPopupMenuEx(HMENU,UINT,INT,INT,HWND,LPTPMPARAMS);//6
BOOL NtUserEndPaint(HWND,LPPAINTSTRUCT);//2
HDESK NtUserOpenInputDesktop(DWORD,BOOL,ACCESS_MASK);//3
DWORD NtGdiDvpGetVideoPortOutputFormats(HANDLE,OUT PDD_GETVPORTOUTPUTFORMATDATA);//2
BOOL NtUserPostThreadMessage(DWORD,UINT,WPARAM,LPARAM);//4
HBRUSH NtGdiCreateHatchBrushInternal(ULONG,COLORREF,BOOL);//3
DWORD NtGdiDdQueryMoCompStatus(HANDLE,OUT PDD_QUERYMOCOMPSTATUSDATA);//2
UINT NtUserGetKeyboardLayoutList(ULONG,LPHKL);//2
NTSTATUS NtGdiDdNotifyFullscreenSpriteUpdate(HDC,HANDLE);//2
INT NtUserMenuItemFromPoint(HWND,HMENU,DWORD,DWORD);//4
NTSTATUS NtGdiEngDeletePath(PATHOBJ*);//1
BOOL NtGdiEngEraseSurface(SURFOBJ*,LPRECTL,ULONG);//3
NTSTATUS NtGdiEngDeleteClip(CLIPOBJ*);//1
IFIMETRICS* NtGdiFONTOBJ_pifi(FONTOBJ*);//1
BOOL NtGdiEngCopyBits(SURFOBJ*,SURFOBJ*,CLIPOBJ*,XLATEOBJ*,LPRECTL,PPOINTL);//6
ULONG NtGdiGetGlyphOutline(HDC,WCHAR,UINT,OUT LPGLYPHMETRICS,ULONG,PVOID,LPMAT2,BOOL);//8
HACCEL NtUserCreateAcceleratorTable(LPACCEL,ULONG);//2
COLORREF NtGdiGetNearestColor(HDC,COLORREF);//2
LRESULT NtUserDispatchMessage(LPMSG);//1
BOOL NtGdiGetDCPoint(HDC,UINT,OUT PPOINTL);//3
BOOL NtUserShowWindow(HWND,LONG);//2
DWORD_PTR NtUserCallOneParam(DWORD_PTR,DWORD);//2
BOOL NtUserEnableScrollBar(HWND,UINT,UINT);//3
DWORD NtGdiDdLock(HANDLE,OUT PDD_LOCKDATA,HDC);//3
INT NtGdiIntersectClipRect(HDC,INT,INT,INT,INT);//5
BOOL NtGdiDdDeleteDirectDrawObject(HANDLE);//1
HWND NtUserSetFocus(HWND);//1
BOOL NtUserDrawCaption(HWND,HDC,LPCRECT,UINT);//4
INT NtGdiGetSpoolMessage(DWORD,DWORD,DWORD,DWORD);//4
ULONG NtUserGetAtomName(ATOM,OUT PUNICODE_STRING);//2
HKL NtUserActivateKeyboardLayout(HKL,ULONG);//2
BOOL NtGdiMirrorWindowOrg(HDC);//1
DWORD NtGdiDdFlipToGDISurface(HANDLE,OUT PDD_FLIPTOGDISURFACEDATA);//2
LONG NtGdiConvertMetafileRect(HDC,OUT PRECTL);//2
DWORD NtGdiDvpCanCreateVideoPort(HANDLE,OUT PDD_CANCREATEVPORTDATA);//2
VOID NtUserSetRipFlags(DWORD,DWORD);//2
BOOL NtGdiStretchBlt(HDC,INT,INT,INT,INT,HDC,INT,INT,INT,INT,DWORD,DWORD);//12
INT NtUserGetClassName(HWND,BOOL,PUNICODE_STRING);//3
BOOL NtUserUpdateLayeredWindow(HWND,HDC,LPPOINT,LPSIZE,HDC,LPPOINT,COLORREF,PBLENDFUNCTION,DWORD,LPRECT);//10
BOOL NtUserSetSystemCursor(HCURSOR,DWORD);//2
BOOL NtUserTranslateMessage(LPMSG,UINT);//2
DWORD NtGdiDdDestroyMoComp(HANDLE,OUT PDD_DESTROYMOCOMPDATA);//2
DWORD NtGdiDvpReleaseNotification(HANDLE,HANDLE);//2
DWORD NtUserExcludeUpdateRgn(HDC,HWND);//2
HPALETTE NtGdiCreatePaletteInternal(LPLOGPALETTE,UINT);//2
ULONG NtGdiDdQueryVisRgnUniqueness(VOID);//0
